services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - PYTHON_VERSION=3.12.4
      - DJANGO_SETTINGS_MODULE=config.settings
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    command: ["/app/entrypoint.sh"]

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_VERSION=18
      - NODE_ENV=development
    command: npm run dev

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - PYTHON_VERSION=3.12.4
      - DJANGO_SETTINGS_MODULE=config.settings
      - DOCKER_CONTAINER=1
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - backend
    command: python manage.py qcluster